[package]
name = "replisdk"
version = "0.1.1"
description = "All in one SDK to develop Replicante ecosystem components in Rust"

edition = "2021"
rust-version = "1.60"

homepage = "https://replicante.io"
license = "MIT"
repository = "https://github.com/replicante-io/replisdk-rust"

# Exclude CI/dev files from cargo packages.
exclude = [
  "/.github",
  "/ci",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
## Platform features
# Enable all platform related features.
platform = ["platform-models"]
# Enable definitions of platform data models.
platform-models = ["serde", "serde_json"]

[dependencies]
serde = { version = "^1.0", optional = true, features = ["derive"] }
serde_json = { version = "^1.0", optional = true }

# Always depend on the proc macros crate matching our exact version!
replisdk-proc = { version = "=0.1.1", path = "./proc"}

[package.metadata.docs.rs]
all-features = true

[workspace]
members = [
  "experimental",
  "experimental-proc",
  "proc",
]
