name: Rust Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Stable rust is the version we aim to use for builds.
  check-stable:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Replicante SDK
        run: ci/check-workspace.sh --full SDK Cargo.toml
      - name: Experimental Replicante SDK
        run: ci/check-workspace.sh --full "Experimental SDK" experimental/Cargo.toml

  # Earliest version of rust supported (breaking clippy check).
  check-min-rust:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.70.0
          override: true
          components: rustfmt, clippy

      - name: Replicante SDK
        run: ci/check-workspace.sh SDK Cargo.toml
      - name: Experimental Replicante SDK
        run: ci/check-workspace.sh "Experimental SDK" experimental/Cargo.toml
